import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { COMPANY } from './supabaseClient';
import { formatDate, formatKES } from './calculations';

/**
 * Generates and downloads a PDF report with the company logo, header info,
 * a per-cereal records table, an expenses table, and grand totals.
 */
export async function exportReportPDF({ fromDate, toDate, records, expenses, totals, cerealsById, generatedBy }) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;

  // ---- Load logo as base64 ----
  let logoData = null;
  try {
    const res = await fetch('/logo.png');
    const blob = await res.blob();
    logoData = await new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result);
      reader.readAsDataURL(blob);
    });
  } catch (e) {
    logoData = null;
  }

  // ---- Header ----
  if (logoData) {
    doc.addImage(logoData, 'PNG', margin, 30, 60, 60);
  }

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(28, 99, 52);
  doc.text(COMPANY.name, margin + 70, 50);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  doc.text(COMPANY.address, margin + 70, 66);
  const contactLine = [COMPANY.phone, COMPANY.email].filter(Boolean).join('   |   ');
  if (contactLine) doc.text(contactLine, margin + 70, 80);

  doc.setDrawColor(28, 99, 52);
  doc.setLineWidth(1.2);
  doc.line(margin, 100, pageWidth - margin, 100);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(20, 20, 20);
  doc.text('Sales & Expenses Report', margin, 122);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Period: ${formatDate(fromDate)}  to  ${formatDate(toDate)}`, margin, 138);
  doc.text(`Generated on: ${new Date().toLocaleString('en-GB')}`, margin, 152);
  if (generatedBy) doc.text(`Generated by: ${generatedBy}`, margin, 166);

  // ---- Cereal Records Table ----
  const recordRows = (records || []).map((r) => {
    const cerealName = cerealsById?.[r.cereal_id]?.name || 'Cereal';
    const buyTotal = Number(r.buying_price) * Number(r.quantity_bought);
    const sellTotal = Number(r.selling_price) * Number(r.quantity_sold);
    return [
      formatDate(r.record_date),
      cerealName,
      `${r.quantity_bought} kg @ ${formatKES(r.buying_price)}`,
      `${r.quantity_sold} kg @ ${formatKES(r.selling_price)}`,
      formatKES(buyTotal),
      formatKES(sellTotal),
      formatKES(sellTotal - buyTotal),
    ];
  });

  autoTable(doc, {
    startY: 182,
    margin: { left: margin, right: margin },
    head: [['Date', 'Cereal', 'Bought', 'Sold', 'Buying Total', 'Selling Total', 'Profit']],
    body: recordRows.length ? recordRows : [['—', 'No records in this period', '', '', '', '', '']],
    headStyles: { fillColor: [28, 99, 52], textColor: 255, fontSize: 8 },
    bodyStyles: { fontSize: 8 },
    alternateRowStyles: { fillColor: [245, 248, 245] },
    styles: { cellPadding: 4 },
  });

  // ---- Expenses Table ----
  let afterRecordsY = doc.lastAutoTable.finalY + 20;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(20, 20, 20);
  doc.text('Expenses', margin, afterRecordsY);

  const expenseRows = (expenses || []).map((e) => [
    formatDate(e.expense_date),
    e.category || 'General',
    e.description || '',
    formatKES(e.amount),
  ]);

  autoTable(doc, {
    startY: afterRecordsY + 10,
    margin: { left: margin, right: margin },
    head: [['Date', 'Category', 'Description', 'Amount']],
    body: expenseRows.length ? expenseRows : [['—', '—', 'No expenses in this period', '']],
    headStyles: { fillColor: [241, 196, 15], textColor: 20, fontSize: 8 },
    bodyStyles: { fontSize: 8 },
    alternateRowStyles: { fillColor: [253, 250, 240] },
    styles: { cellPadding: 4 },
  });

  // ---- Totals Summary ----
  let summaryY = doc.lastAutoTable.finalY + 24;
  if (summaryY > doc.internal.pageSize.getHeight() - 140) {
    doc.addPage();
    summaryY = 60;
  }

  doc.setFillColor(28, 99, 52);
  doc.roundedRect(margin, summaryY, pageWidth - margin * 2, 110, 6, 6, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Summary Totals', margin + 16, summaryY + 22);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  const lines = [
    [`Total Buying Price:`, formatKES(totals.totalBuying)],
    [`Total Selling Price:`, formatKES(totals.totalSelling)],
    [`Gross Profit:`, formatKES(totals.grossProfit)],
    [`Total Expenses:`, formatKES(totals.totalExpenses)],
    [`Net Profit:`, formatKES(totals.netProfit)],
  ];
  let ly = summaryY + 42;
  lines.forEach(([label, value]) => {
    doc.text(label, margin + 16, ly);
    doc.text(value, pageWidth - margin - 16, ly, { align: 'right' });
    ly += 14;
  });

  // ---- Footer ----
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `${COMPANY.name} — Confidential Report — Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 20,
      { align: 'center' }
    );
  }

  doc.save(`WP-Grains-Report_${fromDate}_to_${toDate}.pdf`);
}
