import { useEffect, useState } from 'react';
import ProtectedRoute from '../components/ProtectedRoute';
import Layout from '../components/Layout';
import { supabase } from '../lib/supabaseClient';
import { useAuth } from '../context/AuthContext';

export default function AdminsPage() {
  const { profile } = useAuth();
  const [admins, setAdmins] = useState([]);
  const [loading, setLoading] = useState(true);
  const [editingName, setEditingName] = useState('');
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    load();
  }, []);

  async function load() {
    setLoading(true);
    const { data } = await supabase.from('admin_profiles').select('*').order('created_at');
    setAdmins(data || []);
    setLoading(false);
  }

  async function handleUpdateOwnName() {
    if (!editingName.trim()) return;
    setSaving(true);
    const { error } = await supabase
      .from('admin_profiles')
      .update({ full_name: editingName.trim() })
      .eq('id', profile.id);
    setSaving(false);
    if (error) {
      alert(error.message);
    } else {
      setEditingName('');
      load();
    }
  }

  return (
    <ProtectedRoute>
      <Layout title="System Admins" subtitle="Authorized administrators of W&P Grains Traders.">
        <div className="table-wrap" style={{ marginBottom: 24 }}>
          <table className="data-table">
            <thead>
              <tr>
                <th>Full Name</th>
                <th>Email</th>
                <th>Role</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              {admins.map((a) => (
                <tr key={a.id}>
                  <td>{a.full_name}</td>
                  <td>{a.email}</td>
                  <td>
                    <span className="badge">{a.role}</span>
                  </td>
                  <td>{a.id === profile?.id ? '🟢 You' : 'Active'}</td>
                </tr>
              ))}
            </tbody>
          </table>
          {!loading && admins.length === 0 && (
            <div className="empty-state">
              No admin profiles found yet. Set up Purity Mutuma and Simon via Supabase
              Authentication, then insert their rows into admin_profiles (see supabase/schema.sql).
            </div>
          )}
        </div>

        <div className="card">
          <h3>Update My Display Name</h3>
          <p>This is the name shown on the dashboard and in PDF reports as "Generated by".</p>
          <div className="form-row">
            <div className="form-group" style={{ marginBottom: 0 }}>
              <input
                type="text"
                className="form-control"
                placeholder={profile?.full_name || 'Your name'}
                value={editingName}
                onChange={(e) => setEditingName(e.target.value)}
              />
            </div>
            <button className="btn btn-primary" onClick={handleUpdateOwnName} disabled={saving}>
              {saving ? <span className="spinner" /> : 'Save'}
            </button>
          </div>
        </div>

        <div className="card" style={{ marginTop: 18 }}>
          <h3>Adding / Removing Admins</h3>
          <p>
            For security, new admin accounts must be created from the Supabase Dashboard
            (Authentication → Users → Add user), then linked by inserting a row into the
            <code> admin_profiles</code> table with the matching user ID. Only emails registered
            in <code>admin_profiles</code> can sign in to this system. Full instructions are
            included in <code>supabase/schema.sql</code>.
          </p>
        </div>
      </Layout>
    </ProtectedRoute>
  );
}
